site_name: Euclid's Toolworks Substack
site_url: https://euclidstoolworks.substack.com
theme:
  name: material
  logo: assets/Euclid.jpg
  favicon: assets/Euclid.jpg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

plugins:
  - glightbox
  - blog:
      enabled: true
      blog_dir: .
      post_date_format: yyyy-MM-dd
      post_url_format: "{slug}"
  - rss:
      enabled: true
      match_path: posts/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      abstract_chars_count: 0
      use_page_content: true
      feed_title: Euclid's Toolworks Substack
      feed_url: https://euclidstoolworks.github.io/substack-automation/feed_rss_created.xml
      pretty_print: true


extra:
  social:
    - icon: simple/substack
      link: https://euclidstoolworks.substack.com

copyright: Copyright © 2025 Euclid's Toolworks
