authors:
  me:
    name: Kurt Andrews
    description: "Father, Husband, Mad Computer Scientist, Mathematician, Lay Theologian, Reader, Dragon Believer, Hand Tool Woodworker, I am the geek squad."
    email:
    avatar: https://avatars.githubusercontent.com/u/2064542?v=4
